### ISSUE TITLE
[SUGGESTION] Add a config values to disable or change the style of stats success/failed to send message

### ISSUE THREAD

**Issue by NilaierMusic** [danielmccluskey/LethalStatsMod#2]
I suggest making a config values to completely disable or change the style of the message that pops up on the screen saying that the data were or weren't sent to the website. The reason is, current implementation is a little bit distracting and slightly irritating.

Here's my proposed style of notifications. Would be good to also be able to turn on or off the notification sound in the config.
![CustomStatsSentMessage](https://github.com/danielmccluskey/LethalStatsMod/assets/86863646/f96ca925-74f7-4edd-9583-894f60cdfe68)
Bottom right corner or maybe a custom position.

**Comment by danielmccluskey** [comment]
I have disabled this message completely now so I'll close the issue.
