### ISSUE TITLE
[BUG] Duplicated death cause on the website

### ISSUE THREAD

**Issue by NilaierMusic** [danielmccluskey/LethalStatsMod#3]
You probably already know that, but https://lethal.splitstats.io/globals has a duplicated `Unknown` death cause with different counters respectively.
![image](https://github.com/danielmccluskey/LethalStatsMod/assets/86863646/e32fc7ae-4eb5-4f4d-973c-fc42ca5dd5f0)

**Comment by danielmccluskey** [comment]
The latest update to the site doesn't have this page public right now, but it is fixed. Thanks for letting me know :)
