### ISSUE TITLE
[Bug] Lethal Stats fails to properly record first match of the session

### ISSUE THREAD

**Issue by ajsglist** [danielmccluskey/LethalStatsMod#4]
Hey there, I've been using Lethal Stats for a bit now and the mod is excellent!

One major issue that's popped up, though: The first game never seems to be properly recorded.  Despite getting the popup about the stats being sent successfully.  Every day appears to be recorded except the first, which always fails to get recorded on the website.

Thanks again for the mod, it's a great feature

**Comment by danielmccluskey** [comment]
Managed to fix this finally on my lunch break today. Was an issue with the API not accepting it.
